

mweb_admin:
    path: /
    defaults: {_controller: MwebAdminBundle:Manage:index}


mweb_admin_list_entity:
    path: /list/{entityAlias}
    defaults: {_controller: MwebAdminBundle:Manage:list}


mweb_admin_edit_position_entity:
    path: /edit/positions/{entityAlias}
    defaults: {_controller: MwebAdminBundle:Manage:editPosition}

mweb_admin_edit_entity:
    path: /edit/{_locale}/{entityAlias}/{id}
    defaults: {_controller: MwebAdminBundle:Manage:edit}

mweb_admin_view_entity:
    path: /view/{entityAlias}/{id}
    defaults: {_controller: MwebAdminBundle:Manage:view}

        
mweb_admin_delete_entity:
    path: /delete/{entityAlias}/{id}
    defaults: {_controller: MwebAdminBundle:Manage:delete}

mweb_admin_tinymce_browser:
    path:  /tinymceBrowser/{file}
    defaults: { _controller: MwebAdminBundle:Tinymce:browser, file: null }
    requirements:
        file: .+

mweb_admin_user_edit:
    path:  /user/edit/{userId}
    defaults: { _controller: MwebAdminBundle:User:edit}

mweb_admin_user_list:
    path:  /user/list
    defaults: { _controller: MwebAdminBundle:User:list}

mweb_admin_update_cache:
    path: /updatecache
    defaults: {_controller: MwebAdminBundle:Manage:updateCache}

mweb_admin_update_status_website:
    path: /updatestatuswebsite
    defaults: {_controller: MwebAdminBundle:Manage:updateStatusWebsite}

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix: /trans